# Generated by Django 4.2.1 on 2023-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_parking', models.IntegerField()),
                ('parking_limit', models.IntegerField()),
                ('parking_number_ratio', models.IntegerField()),
            ],
        ),
    ]
